FROM node:12.2.0-alpine
MAINTAINER "János Gats <gatsjanos@gmail.com>"

ENV APP_HOME=/app

RUN mkdir -p ${APP_HOME}

WORKDIR ${APP_HOME}

#COPY ./node_modules ${APP_HOME}/node_modules
VOLUME ${APP_HOME}/node_modules
COPY ./public ${APP_HOME}/public
COPY ./tsconfig.json ${APP_HOME}/tsconfig.json
COPY ./src ${APP_HOME}/src
COPY ./package* ${APP_HOME}/

EXPOSE 30015
EXPOSE 3000


RUN npm install -g serve
CMD ["serve", "-l", "3000", "-s", "build"]